--------------------------------------------------------
--  File created - понедельник-окт€бр€-23-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "ROOT"."PERSON" 
   (	"PERSON_ID" NUMBER(19,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"SURNAME" VARCHAR2(30 BYTE), 
	"LOGIN" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"ACTIVE" NUMBER(10,0), 
	"EXPERIENCE" DATE, 
	"POSITION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSON_ROLE
--------------------------------------------------------

  CREATE TABLE "ROOT"."PERSON_ROLE" 
   (	"PERSON_ROLE_ID" NUMBER(19,0), 
	"PERSON_ID" NUMBER(19,0), 
	"ROLE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "ROOT"."ROLE" 
   (	"ROLE_ID" NUMBER(19,0), 
	"ROLE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "ROOT"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into ROOT.PERSON
SET DEFINE OFF;
Insert into ROOT.PERSON (PERSON_ID,NAME,SURNAME,LOGIN,PASSWORD,ACTIVE,EXPERIENCE,POSITION) values ('1','Name','Surname','surname@tut.by','12345678900','1',to_date('08.10.17','DD.MM.RR'),'SENIOR');
Insert into ROOT.PERSON (PERSON_ID,NAME,SURNAME,LOGIN,PASSWORD,ACTIVE,EXPERIENCE,POSITION) values ('5','alex','alex1','surname3@tut.by','0987654321','1',to_date('18.10.17','DD.MM.RR'),'MIDDLE');
REM INSERTING into ROOT.PERSON_ROLE
SET DEFINE OFF;
Insert into ROOT.PERSON_ROLE (PERSON_ROLE_ID,PERSON_ID,ROLE_ID) values ('1','1','1');
Insert into ROOT.PERSON_ROLE (PERSON_ROLE_ID,PERSON_ID,ROLE_ID) values ('6','5','2');
REM INSERTING into ROOT.ROLE
SET DEFINE OFF;
Insert into ROOT.ROLE (ROLE_ID,ROLE) values ('1','ADMIN');
Insert into ROOT.ROLE (ROLE_ID,ROLE) values ('2','USER');
--------------------------------------------------------
--  DDL for Index UK_6SE522AJAOQHX5BPK7OBDQ1BU
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."UK_6SE522AJAOQHX5BPK7OBDQ1BU" ON "ROOT"."PERSON" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "ROOT"."PERSON" ADD CONSTRAINT "UK_6SE522AJAOQHX5BPK7OBDQ1BU" UNIQUE ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOT"."PERSON" ADD PRIMARY KEY ("PERSON_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOT"."PERSON" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."PERSON" MODIFY ("EXPERIENCE" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."PERSON" MODIFY ("ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."PERSON" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."PERSON" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."PERSON" MODIFY ("SURNAME" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."PERSON" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."PERSON" MODIFY ("PERSON_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "ROOT"."ROLE" ADD PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOT"."ROLE" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSON_ROLE
--------------------------------------------------------

  ALTER TABLE "ROOT"."PERSON_ROLE" ADD PRIMARY KEY ("PERSON_ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROOT"."PERSON_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."PERSON_ROLE" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "ROOT"."PERSON_ROLE" MODIFY ("PERSON_ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "ROOT"."PERSON" ADD CONSTRAINT "FK_TCH55IYWY87IH28WJABGDV0DH" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "ROOT"."PERSON" ("PERSON_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSON_ROLE
--------------------------------------------------------

  ALTER TABLE "ROOT"."PERSON_ROLE" ADD CONSTRAINT "FK_BBCMIDLLDDJWHNQIXSVF2RTJR" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "ROOT"."PERSON" ("PERSON_ID") ENABLE;
  ALTER TABLE "ROOT"."PERSON_ROLE" ADD CONSTRAINT "FK_TQNCVT8MKPL7VKF04BPYJ0O0K" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "ROOT"."ROLE" ("ROLE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "ROOT"."ROLE" ADD CONSTRAINT "FK_83R38KV6T5KYN621PA9DONXMG" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "ROOT"."ROLE" ("ROLE_ID") ENABLE;
